#配置数据源的属性
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/bookmanagement?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      username: root
      password: 123456
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validationQuery: SELECT 'x'   #验证连接
      enable: true
   #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
  #thymeleaf的配置
  thymeleaf:
    cache: false
    enabled: true   # 禁用缓存
#      web-stat-filter:
#        enabled: true
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    # 限制附件上传大小
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

#配置mybatisplus
mybatis-plus:
  mapper-locations:
  - classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#shiro的配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  anon-urls:
  - /index.html*    # 浏览器访问页面
  - /sys/toLogin*   # 跳转至登录页面
  - /login/generate # 生成验证码
  - /login/login*   # 核对用户身份
  - /resources/**
  - /v2/**    # swagger 相关静态资源路径
  - /swagger-resources/**
  - /swagger-ui.html
  - /webjars/**
  login-url: /index.html
  log-out-url: /login/logout*
  authc-ulrs:
  - /**


